
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api';

export const API_ENDPOINTS = {

  REGISTER: '/auth/register',
  LOGIN: '/auth/login',
  REFRESH_TOKEN: '/auth/refresh-token',
  OTP_REQUEST: '/auth/otp/request',
  OTP_VERIFY: '/auth/otp/verify',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',

  GET_ME: '/user/me',
  UPDATE_PROFILE: '/user/profile',
  CHANGE_PASSWORD: '/user/change-password',
  DELETE_ACCOUNT: '/user/delete',

  DASHBOARD: '/dashboard',

  CLASSROOM_CREATE: '/classroom/create',
  CLASSROOM_ALL: '/classroom/all',
  CLASSROOM_MEMBERS: (classCode) => `/classroom/${classCode}/members`,
  CLASSROOM_DELETE: (classCode) => `/classroom/${classCode}`,
  CLASSROOM_JOIN_REQUEST: (classCode) => `/classroom/${classCode}/join-request`,
  CLASSROOM_ACCEPT: (classCode, requestId) => `/classroom/${classCode}/accept/${requestId}`,
  CLASSROOM_REJECT: (classCode, requestId) => `/classroom/${classCode}/reject/${requestId}`,
  CLASSROOM_ACCEPT_ALL: (classCode) => `/classroom/${classCode}/accept-all`,
  CLASSROOM_REJECT_ALL: (classCode) => `/classroom/${classCode}/reject-all`,
  CLASSROOM_LEAVE: (classCode) => `/classroom/${classCode}/leave`,
  CLASSROOM_REMOVE_MEMBER: (classCode, memberId) => `/classroom/${classCode}/members/${memberId}`,
  CLASSROOM_PENDING_REQUESTS: '/classroom/pending-requests',
  CLASSROOM_DETAIL: (classCode) => `/classroom/${classCode}`,

  MESSAGE_SEND: (classCode) => `/message/${classCode}/send`,
  MESSAGE_GET: (classCode) => `/message/${classCode}/messages`,
  MESSAGE_DELETE: (messageId) => `/message/${messageId}`,

  DOCUMENT_ALL: '/document/all',
  DOCUMENT_UPLOAD: (numQuestions, mode) => `/document/upload/${numQuestions}?mode=${mode}`,
  DOCUMENT_SAVE_QUESTIONS: (documentId) => `/document/save-questions/${documentId}`,
  DOCUMENT_DELETE: (documentId) => `/document/${documentId}`,
  DOCUMENT_QUESTION_COUNT: (documentId) => `/document/${documentId}/question-count`,

  QUESTION_CREATE: '/question/create',
  QUESTION_ALL: '/question/all',
  QUESTION_SUBJECTS: '/question/subject/list',
  QUESTION_GET: (questionId) => `/question/${questionId}`,
  QUESTION_UPDATE: (questionId) => `/question/${questionId}`,
  QUESTION_DELETE: (questionId) => `/question/${questionId}`,

  EXAM_CREATE: '/exam/create',
  EXAM_ALL: '/exam/all',
  EXAM_BY_CLASS: (classId) => `/exam/class/${classId}`,
  EXAM_DELETE: (examId) => `/exam/${examId}`,
  EXAM_GET: (examId) => `/exam/${examId}`,
  EXAM_START: (examId) => `/exam/${examId}/start`,
  EXAM_SUBMIT: (examId) => `/exam/${examId}/submit`,
  EXAM_PREVIEW: '/exam/preview',
  EXAM_REPLACE_QUESTION: '/exam/replace-question',

  RESULT_ALL: '/result/all',
  RESULT_BY_EXAM: (examId) => `/result/exam/${examId}`,
  RESULT_BY_CLASS: (classId) => `/result/class/${classId}`,
  RESULT_DELETE: (resultId) => `/result/${resultId}`,

  STATS_BY_EXAM: (examId) => `/statistics/exam/${examId}`,
  STATS_BY_CLASS: (classId) => `/statistics/class/${classId}`,
  STATS_PERSONAL: '/statistics/personal',
  STATS_OVERALL: '/statistics/overall',
  STATS_COMPREHENSIVE: '/statistics/comprehensive',
  STATS_STUDENT_COMPREHENSIVE: '/statistics/student/comprehensive',
  STATS_TEACHER_COMPREHENSIVE: '/statistics/teacher/comprehensive',
  STATS_EXAM_DETAILED: (examId) => `/statistics/exam/${examId}/detailed`,
  STATS_CLASS_DETAILED: (classId) => `/statistics/class/${classId}/detailed`,
  STATS_PLATFORM: '/statistics/platform',

  NOTIFICATIONS_GET: '/notifications/',
  NOTIFICATIONS_UNREAD_COUNT: '/notifications/unread-count',
  NOTIFICATIONS_MARK_READ: '/notifications/mark-read',
  NOTIFICATIONS_DELETE: (notificationId) => `/notifications/${notificationId}`,
  NOTIFICATIONS_DELETE_ALL: '/notifications/',

  PRACTICE_CREATE: '/practice/exam/create',
  PRACTICE_GET_EXAMS: '/practice/exams',
  PRACTICE_START: (examId) => `/practice/exam/${examId}/start`,
  PRACTICE_SUBMIT: (examId) => `/practice/exam/${examId}/submit`,
  PRACTICE_DELETE: (examId) => `/practice/exam/${examId}`,
  PRACTICE_STATS: '/practice/statistics',
  PRACTICE_STATS_DETAILED: '/practice/statistics/detailed',
  PRACTICE_EXAM_STATS: (examId) => `/practice/exam/${examId}/statistics`,
  PRACTICE_DOCUMENT_STATS: '/practice/documents/statistics',

  ADMIN_USERS: '/admin/users/',
  ADMIN_USER_CREATE: '/admin/users/create',
  ADMIN_USER_GET: (userId) => `/admin/users/${userId}`,
  ADMIN_USER_UPDATE: (userId) => `/admin/users/${userId}`,
  ADMIN_USER_DELETE: (userId) => `/admin/users/${userId}`,
  ADMIN_USER_STATUS: (userId) => `/admin/users/${userId}/status`,
  ADMIN_CLASSROOM_GET: (classroomId) => `/admin/classroom/${classroomId}`,
  ADMIN_CLASSROOM_UPDATE: (classroomId) => `/admin/classroom/${classroomId}`,
  ADMIN_CLASSROOM_DELETE: (classroomId) => `/admin/classroom/${classroomId}`,
  ADMIN_LOGS: '/admin/logs/',
  ADMIN_LOG_STATS: '/admin/logs/statistics',
  ADMIN_LOG_GET: (logId) => `/admin/logs/${logId}`,
  ADMIN_LOG_CLEANUP: '/admin/logs/cleanup',
  ADMIN_NOTIFICATIONS: '/admin/notifications/system-notifications',
  ADMIN_SYSTEM_HEALTH: '/admin/notifications/system-health',
  ADMIN_CLEANUP_NOTIFICATIONS: '/admin/notifications/cleanup-notifications',
  ADMIN_TEST_NOTIFICATION: '/admin/notifications/test-notification',

  ADMIN_STATISTICS: '/admin/stats/statistics',
  ADMIN_USER_ACTIVITY: (userId) => `/admin/stats/users/${userId}/activity`,
  ADMIN_USER_GROWTH: '/admin/stats/analytics/user-growth',
  ADMIN_ACTIVITY_HEATMAP: '/admin/stats/analytics/activity-heatmap',
};

export default API_BASE_URL;
